# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vDbjsBTNf4zyliovz7FVK2efUXXw3wE

from google.colab import files
uploaded = files.upload()
"""

# -------------------------------------------------------------------------
# AUTHOR: EARAGA
# FILENAME: title of the source file
# SPECIFICATION: description of the program
# FOR: CS 4440 (Data Mining) - Assignment #2
# TIME SPENT: 29MIN
# -----------------------------------------------------------*/
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Step 1: Load dataset
data = pd.read_csv('heart_disease_dataset.csv')

# Step 2: Separate numeric features only (if labels exist)
X = data.select_dtypes(include=['float64', 'int64'])

# Standardize features (as in Lecture 3, Step 1 of PCA)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 3: Apply PCA multiple times, removing one feature each time
pca_variances = []

for i, feature in enumerate(X.columns):
    # Remove the i-th feature
    X_reduced = X.drop(columns=[feature])

    # Standardize again
    Xr_scaled = scaler.fit_transform(X_reduced)

    # Apply PCA (Lecture Step 3–5)
    pca = PCA(n_components=1)
    pca.fit(Xr_scaled)

    # Record variance explained by PC1
    pc1_var = pca.explained_variance_ratio_[0]
    pca_variances.append(pc1_var)

    print(f"Removed Feature: {feature:20s} | PC1 Variance: {pc1_var:.4f}")

# Step 4: Find maximal PC1 variance observed
max_var = max(pca_variances)
best_feature_removed = X.columns[pca_variances.index(max_var)]

print("\n------------------------------------------")
print(f"Maximum PC1 Variance: {max_var:.4f}")
print(f"Feature Removed for Max Variance: {best_feature_removed}")
print("------------------------------------------")